version: '2'
services:
  web:
    build: ./
    tty: true
    restart: always
    volumes:
      - './:/usr/app'
    ports:
      - '8083:3001'
  mongo:
    image: mongo
    ports:
      - '8084:27017'
